# -*- coding: utf-8 -*-
"""OFDM_Simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hs_8O4n2UrjV1BMYbhvihT9tyTAkwwZJ
"""

# Commented out IPython magic to ensure Python compatibility.
#OFDM Modulation Simulation
#Projec 2 - VoicceForge Portfolio
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

#Cell 2:OFDM System Parameters
N = 64 #number of subcarriers (frequency lanes)
num_bits = 64 #bits per OFDM symbol
snr_range = range(0,21,2) #snr from 0 to 20db

print(f"Subcarriers:{N}")
print(f"Bits per symbol:{num_bits}")
print(f"SNR range : 0 to 20db")
print(f"Modulation:BPSK")

#BPSK Modulation and Demodulation functions

def bpsk_modulate(bits):
  #Convert bits to symbols
  #0 -> -1, 1->+1
  return 2*bits-1

def bpsk_demodulate(symbols):
  #convert symbols back to bits
  #positive ->1,negative ->0
  return (symbols>0).astype(int)
#test it
tests_bits = np.array([0,1,1,0,1])
tests_symbols = bpsk_modulate(tests_bits)
recovered = bpsk_demodulate(tests_symbols)

print(f"Original bits :{tests_bits}")
print(f"BPSK symbols:{tests_symbols}")
print(f"Recovered bits:{recovered}")
print(f"Match:{np.array_equal(tests_bits,recovered)}")

#OFDM Transmitter
def ofdm_transmit(bits):
  #step 1:bpsk modulate bits to symbol
  symbols = bpsk_modulate(bits)

  #step 2:IFFT-put symbols onto subcarriers
  time_signal = np.fft.ifft(symbols)

  return time_signal

#test it
tests_bits = np.random.randint(0,2,N)
transmitted = ofdm_transmit(tests_bits)

print(f"Input bits shape : {tests_bits.shape}")
print(f"Transmitted signal shape : {transmitted.shape}")
print(f"First 5 bits : {tests_bits[:5]}")
print(f"First 5 tx samples : {np.round(transmitted[:5],4)}")

#cell 5 - AWGN Channel(Add Noise)
#add noise to simulate real wireless

def add_awgn_noise(signal,snr_db):

  #convert SNR from db to linear scale
  snr_linear = 10**(snr_db/10)

  #Calculate signal power
  signal_power = np.mean(np.abs(signal)**2)

  #Calculate noise power
  noise_power = signal_power/snr_linear

  #Generate  complex  Gaussian  noise
  noise = np.sqrt(noise_power/2)*(np.random.randn(len(signal)) + 1j*np.random.randn(len(signal)))

  #add noise to signal
  return signal + noise


#test it
snr_test = 10 #10 db SNR
noisy_signal =  add_awgn_noise(transmitted,  snr_test)

print(f"Clean Signal Power : {np.mean(np.abs(transmitted)**2):.4f}")
print(f"Noisy Signal Power : {np.mean(np.abs(noisy_signal)**2):.4f}")
print(f"SNR tested : {snr_test} dB")

#OFDM reciever

def ofdm_recieve(recieved_signal):

  #step 1: FFT - extract symbols from subcarriers
  symbols = np.fft.fft(recieved_signal)

  #step 2:  BPSK demodulate symbols back to bits
  bits = bpsk_demodulate(symbols.real)

  return bits

#test it-full  pipeline once
tests_bits = np.random.randint(0,2,N)
transmitted = ofdm_transmit(tests_bits)
noisy = add_awgn_noise(transmitted,snr_db = 10)
recieved = ofdm_recieve(noisy)

#count errors
errors = np.sum(tests_bits != recieved)
ber = errors/N

print(f"Bits sent : {tests_bits[:10]}")
print(f"Bits recieved : {recieved[:10]}")
print(f"Errors : {errors}")
print(f"BER : {ber:.4f}")

# Cell 7: BER vs SNR curve

ber_results = []
num_trials  = 1000  # repeat 1000 times per SNR for accuracy

for snr_db in snr_range:
    total_errors = 0
    total_bits   = 0

    for _ in range(num_trials):
        # Generate random bits
        bits = np.random.randint(0, 2, N)

        # Transmit
        tx = ofdm_transmit(bits)

        # Add noise
        rx_noisy = add_awgn_noise(tx, snr_db)

        # Receive
        rx_bits = ofdm_recieve(rx_noisy)

        # Count errors
        total_errors += np.sum(bits != rx_bits)
        total_bits   += N

    # Calculate BER for this SNR
    ber = total_errors / total_bits
    ber_results.append(ber)
    print(f"SNR: {snr_db:2d} dB | BER: {ber:.6f} | Errors: {total_errors}/{total_bits}")

print("\n✅ BER simulation complete!")

# Cell 8: Plot BER vs SNR

snr_list = list(snr_range)

plt.figure(figsize=(10, 6))

# Plot simulated BER
plt.semilogy(
    snr_list,
    [max(b, 1e-6) for b in ber_results],
    'bo-',
    linewidth=2,
    markersize=8,
    label='Simulated BPSK-OFDM'
)

plt.title('OFDM BER vs SNR — BPSK Modulation', fontsize=14)
plt.xlabel('SNR (dB)', fontsize=12)
plt.ylabel('Bit Error Rate (BER)', fontsize=12)
plt.grid(True, which='both', alpha=0.3)
plt.legend(fontsize=11)
plt.xlim(0, 20)
plt.ylim(1e-6, 1)

plt.tight_layout()
plt.savefig('ofdm_ber_curve.png', dpi=150)
plt.show()

print("✅ Saved ofdm_ber_curve.png")

# Cell 9: Constellation Diagram

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Generate fresh test signal
bits        = np.random.randint(0, 2, N)
tx          = ofdm_transmit(bits)

# Low SNR — noisy constellation
rx_low  = np.fft.fft(add_awgn_noise(tx, snr_db=2))
axes[0].scatter(rx_low.real, rx_low.imag,
                color='tomato', alpha=0.6, s=50)
axes[0].axvline(x=0, color='black', linewidth=1)
axes[0].axhline(y=0, color='black', linewidth=1)
axes[0].set_title('Constellation — SNR 2dB (Noisy)', fontsize=12)
axes[0].set_xlabel('In-Phase (Real)')
axes[0].set_ylabel('Quadrature (Imaginary)')
axes[0].grid(True, alpha=0.3)
axes[0].set_xlim(-3, 3)
axes[0].set_ylim(-3, 3)

# High SNR — clean constellation
rx_high = np.fft.fft(add_awgn_noise(tx, snr_db=20))
axes[1].scatter(rx_high.real, rx_high.imag,
                color='steelblue', alpha=0.6, s=50)
axes[1].axvline(x=0, color='black', linewidth=1)
axes[1].axhline(y=0, color='black', linewidth=1)
axes[1].set_title('Constellation — SNR 20dB (Clean)', fontsize=12)
axes[1].set_xlabel('In-Phase (Real)')
axes[1].set_ylabel('Quadrature (Imaginary)')
axes[1].grid(True, alpha=0.3)
axes[1].set_xlim(-3, 3)
axes[1].set_ylim(-3, 3)

plt.suptitle('BPSK Constellation Diagram', fontsize=14)
plt.tight_layout()
plt.savefig('ofdm_constellation.png', dpi=150)
plt.show()

print("✅ Saved ofdm_constellation.png")

# Cell 10: Final summary plot — all results together

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Plot 1 — transmitted signal
tx_plot = ofdm_transmit(np.random.randint(0, 2, N))
axes[0,0].plot(tx_plot.real, color='steelblue', linewidth=1.2)
axes[0,0].set_title('OFDM Transmitted Signal — Time Domain')
axes[0,0].set_xlabel('Sample')
axes[0,0].set_ylabel('Amplitude')
axes[0,0].grid(True, alpha=0.3)

# Plot 2 — frequency domain (subcarriers)
axes[0,1].stem(np.abs(np.fft.fft(tx_plot)),
               linefmt='orange', markerfmt='o', basefmt='k')
axes[0,1].set_title('OFDM Subcarriers — Frequency Domain')
axes[0,1].set_xlabel('Subcarrier Index')
axes[0,1].set_ylabel('Magnitude')
axes[0,1].grid(True, alpha=0.3)

# Plot 3 — BER vs SNR
axes[1,0].semilogy(
    list(snr_range),
    [max(b, 1e-6) for b in ber_results],
    'bo-', linewidth=2, markersize=8
)
axes[1,0].set_title('BER vs SNR Curve')
axes[1,0].set_xlabel('SNR (dB)')
axes[1,0].set_ylabel('BER')
axes[1,0].grid(True, which='both', alpha=0.3)

# Plot 4 — clean constellation
bits    = np.random.randint(0, 2, N)
tx      = ofdm_transmit(bits)
rx_high = np.fft.fft(add_awgn_noise(tx, snr_db=20))
axes[1,1].scatter(rx_high.real, rx_high.imag,
                  color='#2A9D8F', alpha=0.7, s=60)
axes[1,1].axvline(x=0, color='black', linewidth=1)
axes[1,1].axhline(y=0, color='black', linewidth=1)
axes[1,1].set_title('BPSK Constellation — SNR 20dB')
axes[1,1].set_xlabel('In-Phase')
axes[1,1].set_ylabel('Quadrature')
axes[1,1].grid(True, alpha=0.3)

plt.suptitle('OFDM Simulation — Complete Results',
             fontsize=16, fontweight='bold')
plt.tight_layout()
plt.savefig('ofdm_summary.png', dpi=150)
plt.show()

print("✅ Saved ofdm_summary.png")
print("\n🎉 OFDM Project Complete!")
print(f"SNR threshold : ~10 dB")
print(f"Subcarriers   : {N}")
print(f"Modulation    : BPSK")
print(f"Trials        : 1000 per SNR point")

# Download all OFDM files

from google.colab import files

files.download('ofdm_ber_curve.png')
files.download('ofdm_constellation.png')
files.download('ofdm_summary.png')

print("✅ All OFDM files downloaded!")

